### ISSUE TITLE
[IMPORTANT] @Secured an alle Mappings

### ISSUE THREAD

**Issue by iamkawaiineko** [hhu-propra2/abschlussprojekt-proprastination#160]
Momentan gibt es noch viele Mappings in den Controllern die nicht secured sind!

**Comment by iamkawaiineko** [comment]
ich mach erstmal ApplicationController fertig, da ich nicht weiß, was mit den anderen Controllern ist. Vielleicht kann dort jemand anderes gucken?

**Comment by sotgasotga** [comment]
nichts gefunden was noch secured werden müsste
