### ISSUE TITLE
Organisator - Telefonnummer bearbeiten/speichern

### ISSUE THREAD

**Issue by anloe109** [hhu-propra2/abschlussprojekt-proprastination#194]
Bei den persönlichen Daten ist bisher nur ein Popup, wo man die Telefonnummer eingeben kann, die wird aber nirgends ausgelesen oder abgespeichert, soweit ich weiß

**Comment by iamkawaiineko** [comment]
ich Gaube es macht sinn, dass der bearbeiten Button dort nicht gegeben ist und die Änderung im KeyCloak Account erfolgt, dort kommt die Telefonnummer nämlich her
