### ISSUE TITLE
NullPointerException, while logged in as Bewerbung2_all_roles

### ISSUE THREAD

**Issue by iamkawaiineko** [hhu-propra2/abschlussprojekt-proprastination#233]
NullPointer exception: zum  rekreieren: Ich habe alle Module gelöscht, neue erstellt und wollte mich nun für eines der jenigen anmelden

![image](https://user-images.githubusercontent.com/33419720/77686548-6a2b6980-6f9d-11ea-9801-8b610d639d7b.png)
![image](https://user-images.githubusercontent.com/33419720/77686575-77485880-6f9d-11ea-8cc2-870859ecdee4.png)

**Comment by iamkawaiineko** [comment]
nachdem ich nochmal ein Modul erstellt habe (auch in der Rolle bewerbung2_all_roles und dann auf Bewerberansicht gegangen bin und eine neue Bewerbung erstellen wollte habe ich den gleichen Fehler bekommen

![image](https://user-images.githubusercontent.com/33419720/77688115-d3ac7780-6f9f-11ea-9e02-d380a0c82e25.png)
![image](https://user-images.githubusercontent.com/33419720/77688138-dc04b280-6f9f-11ea-90a3-0de8adb21cd9.png)

**Comment by iamkawaiineko** [comment]
Die Methode ist es wohl

![image](https://user-images.githubusercontent.com/33419720/77688285-19694000-6fa0-11ea-8c81-ccc7487caa47.png)

**Comment by iamkawaiineko** [comment]
melde ich mich in der gleichen session als jemand anderes an geht es aber zumindest bis zur Persönlichen Datenanzeige
![image](https://user-images.githubusercontent.com/33419720/77688490-7238d880-6fa0-11ea-97f5-d629911b8d9f.png)

**Comment by iamkawaiineko** [comment]
das Modul darf ich trotzdem nicht ausfüllen
![image](https://user-images.githubusercontent.com/33419720/77688536-85e43f00-6fa0-11ea-92b8-cab7f6417213.png)

![image](https://user-images.githubusercontent.com/33419720/77688550-8ed51080-6fa0-11ea-9af0-f76cf889fb6f.png)

**Comment by iamkawaiineko** [comment]
Zur Bewerbungsübersicht darf ich danach auch nicht mehr

**Comment by iamkawaiineko** [comment]
passiert, als ich einfach nur ein Modul bearbeiten wollte als bewerbung2_all_roles im Organisator dashboard

![image](https://user-images.githubusercontent.com/33419720/77741910-efeafb80-7015-11ea-8bd7-b53ae897b613.png)
![image](https://user-images.githubusercontent.com/33419720/77741936-f8dbcd00-7015-11ea-8d2d-ea87a00f30df.png)

**Comment by ammon-s** [comment]
Wird durch eine nicht vorhandene deadline geworfen (Module.deadline -> null)
Die Deadline wird beim speichern von neuen/bearbeiteten Modulen nicht gesetzt

**Comment by ammon-s** [comment]
Sollte durch deadline Änderung behoben worden sein.
