### ISSUE TITLE
Setup Module Overview not optimal

### ISSUE THREAD

**Issue by iamkawaiineko** [hhu-propra2/abschlussprojekt-proprastination#234]
Sollen wir denn jetzt Maximal Stundenanzahl haben oder die weglassen? Momentan sieht das etwas... komisch aus, wenn man die setzt :d 

![image](https://user-images.githubusercontent.com/33419720/77686792-c2626b80-6f9d-11ea-9bee-b26137d10e7f.png)

**Comment by JuliaBlck** [comment]
Achso ne die kommt weg, Nemo hatte das bei sich auf dem Brach glaub ich auch schon gemacht oder?

**Comment by nemanjaZed** [comment]
ich hatte einen branch mit dem Bewerbungszeiten wo ich das weggemacht hatte. aber ich hatte das im service nicht hinbekommen gehabt und hab das dann auch nicht gepusht. ich kann das eben wegmachen.

**Comment by iamkawaiineko** [comment]
könnt dann ja selber eben gucken ^^

**Comment by iamkawaiineko** [comment]
closed with #244
